import "./globals.css";
import { ThemeProvider } from "next-themes";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ThemeToggle from "../components/ThemeToggle";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "PostGen AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} bg-background text-foreground transition-colors duration-300`}
      >
        {/* Wrap everything inside ThemeProvider */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* <header className="p-6 flex justify-end"> */}
            {/* Your toggle button */}
            {/* <ThemeToggle /> */}
          {/* </header> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
